"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
${custom.git_dirty}\
$git_status\
$cmd_duration\
$status\
$character"""

[character]
success_symbol = '[❱](bold)'
error_symbol = '[❱](bold red)'

[cmd_duration]
format = '[$duration]($style) '
style = ''

[directory]
format = '[$path]($style) '
style = 'bold'
truncation_length = 3
fish_style_pwd_dir_length = 1
repo_root_format = '[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style) '

[git_branch]
format = '$branch'

[custom.git_dirty]
description = "Displays if there are any pending changes in Git's working directory"
command = "test -z $(git status --porcelain) && echo '' || echo •"
when = 'git rev-parse --is-inside-work-tree'
format = '[$output ]($style)'
style = ''
require_repo = true

[git_status]
format = '[$ahead_behind]($style)'
style = ''
diverged = '↑$ahead_count ↓$behind_count '
behind = '↓$count '
ahead = '↑$count '

[status]
disabled = false
format = '[$symbol $status]($style) '
symbol = '|'
style = 'red'
